FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .

COPY MySQLDemo/*.csproj ./MySQLDemo/
COPY MySQLDemo.Client/*.csproj ./MySQLDemo.Client/
COPY MySQLDemo.Core/*.csproj ./MySQLDemo.Core/
COPY MySQLDemo.Gateway/*.csproj ./MySQLDemo.Gateway/
COPY MySQLDemo.Resource/*.csproj ./MySQLDemo.Resource/

RUN dotnet restore

# copy everything else and build app
COPY MySQLDemo.Core/. ./MySQLDemo.Core/
COPY MySQLDemo/. ./MySQLDemo/
WORKDIR /app/MySQLDemo
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
COPY --from=build /app/MySQLDemo/out ./
ENTRYPOINT ["dotnet", "MySQLDemo.dll"]